name: Update RSS Feed

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List repo files for debugging
      run: ls -la

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run RSS generator script
      run: python generate_rss1.py

    - name: Commit updated RSS feed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add rss.xml
        git commit -m "Update RSS feed" || echo "No changes to commit"
        git push
